name: epipolar-consistency # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Consistency Conditions for any two X-ray images. # 79 char long summary
description: Consistency Conditions for any two X-ray images. |
   This project provides both GPU and CPU implementations in C++/CUDA of the Epipolar Consistency Metric. The CPU version relies on Eigen 3 library and follows the 2016 CT-Meeting paper "Efficient Epipolar Consistency" by Aichert et al.

    The projects contained in this repository use the CMake build environment. You can use CMake to generate Visual Studio projects for Windows or makefiles for Linux and MacOS. All libraries used are available on all three platforms and the projects should build with very few fixes in source code.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  nrrdView:
    command: nrrdView

parts:
  libgetset:
    source: https://github.com/aaichert/LibGetSet.git
    plugin: cmake

  epipolar-consistency:
    plugin: cmake
    build-packages:
     - libpng-dev
     - libqt5svg5-dev
     - libomp-dev
     - zlib1g-dev
     - libqt5opengl5-dev
     - libeigen3-dev
     - libgl1-mesa-dev
     - libqt5widgets5
     - libqt5core5a
     - libgraphite2-dev
     - libx11-dev

    after: 
     - libgetset
