name: epipolar-consistency # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Consistency Conditions for any two X-ray images. # 79 char long summary
description: Consistency Conditions for any two X-ray images. |
   Copyrights Andre Aichert, aaichert@gmail.com, andre.aichert@cs.fau.de

   This project provides both GPU and CPU implementations in C++/CUDA of the Epipolar Consistency Metric. The CPU version relies on Eigen 3 library and follows the 2016 CT-Meeting paper "Efficient Epipolar Consistency" by Aichert et al.

   The projects contained in this repository use the CMake build environment. You can use CMake to generate Visual Studio projects for Windows or makefiles for Linux and MacOS. All libraries used are available on all three platforms and the projects should build with very few fixes in source code.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - build-on: [amd64, i386]
apps:
  nrrdView:
    command: desktop-launch nrrdView
    plugs:
     - opengl
     - hardware-observe
     - x11
     - home
     - wayland

  TrajectoryView:
    command: desktop-launch TrajectoryView
    plugs:
     - opengl
     - hardware-observe
     - x11
     - home
     - wayland

parts:
  libgetset:
    source: https://github.com/aaichert/LibGetSet.git
    plugin: cmake
    
  eigen3:
    source: http://bitbucket.org/eigen/eigen/get/3.2.10.tar.bz2
    plugin: cmake
    prime: [ -* ]
    #
  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

  epipolar-consistency:
    source: https://github.com/theHamsta/EpipolarConsistency.git
    plugin: cmake
    build-packages:
     - libpng-dev
     - libqt5svg5-dev
     - libomp-dev
     - zlib1g-dev
     - libqt5opengl5-dev
     - libeigen3-dev
     - libqt5widgets5
     - libqt5core5a
     - libgraphite2-dev
     - freeglut3-dev
     - libx11-dev
     - libxmu-dev
     - libxi-dev
     - libgl1-mesa-glx
     - libglu1-mesa
     - libglu1-mesa-dev
     - libglfw3-dev
     - libgles2-mesa-dev
     - libqt5printsupport5

    after: 
     - libgetset
     - desktop-qt5
     - eigen3

 #     - cuda-build-deps
